<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Three columns powering the SDK setup verification ceremony:
 *
 * - verified_at: set the first time the SDK successfully completes the
 *   token round-trip. Once set, never cleared. Drives the "Verified" pill.
 * - verify_token: 6-digit numeric token currently outstanding (or NULL if
 *   no verification is pending). Generated by the hub, surfaced in the
 *   modal, sent back by the SDK on the next heartbeat.
 * - verify_token_expires_at: TTL guard. Tokens older than ~5 minutes are
 *   refused so a stale token sitting in someone's terminal can't verify.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('projects', function (Blueprint $table): void {
            $table->timestamp('verified_at')->nullable()->after('last_heartbeat_at');
            $table->char('verify_token', 6)->nullable()->after('verified_at');
            $table->timestamp('verify_token_expires_at')->nullable()->after('verify_token');

            $table->index('verify_token', 'projects_verify_token_idx');
        });
    }

    public function down(): void
    {
        Schema::table('projects', function (Blueprint $table): void {
            $table->dropIndex('projects_verify_token_idx');
            $table->dropColumn(['verified_at', 'verify_token', 'verify_token_expires_at']);
        });
    }
};
